import { ShieldCheck, ShieldX } from "lucide-react";

import { getPublicInvoiceVerification } from "@/actions/invoices";
import { Card } from "@/components/ui/core";
import { formatCurrencyAmount, invoiceStatusLabel } from "@/lib/invoices/core";

type InvoiceVerifyPageProps = {
  params: Promise<{ token: string }>;
};

export const dynamic = "force-dynamic";

export default async function InvoiceVerifyPage({ params }: InvoiceVerifyPageProps) {
  const { token } = await params;
  const invoice = await getPublicInvoiceVerification(token);

  return (
    <main className="flex min-h-screen items-center justify-center bg-[#0a0a0f] px-4 py-10 text-slate-100">
      <Card className="w-full max-w-xl p-8">
        {invoice ? (
          <>
            <div className="mb-6 flex items-center gap-3">
              <div className="rounded-full bg-emerald-500/10 p-3 text-emerald-300">
                <ShieldCheck className="h-7 w-7" />
              </div>
              <div>
                <h1 className="text-2xl font-bold">Invoice Verified</h1>
                <p className="text-sm text-slate-500">Generated by PT Ambara Artha Globaltrans.</p>
              </div>
            </div>
            <dl className="space-y-3 text-sm">
              <VerifyRow label="Invoice number" value={invoice.invoiceNumber || "-"} />
              <VerifyRow label="Issuer" value="PT Ambara Artha Globaltrans" />
              <VerifyRow label="Invoice date" value={invoice.invoiceDate || "-"} />
              <VerifyRow label="Customer" value={invoice.customerName || "-"} />
              <VerifyRow label="Gross total" value={`${invoice.currency || "IDR"} ${formatCurrencyAmount(invoice.total, invoice.currency || "IDR")}`} />
              <VerifyRow label="Net payable" value={`${invoice.currency || "IDR"} ${formatCurrencyAmount(invoice.netPayable, invoice.currency || "IDR")}`} />
              <VerifyRow label="Status" value={invoiceStatusLabel(invoice.effectiveStatus)} />
              <VerifyRow label="Checksum" value={invoice.checksum || "-"} />
            </dl>
            <p className="mt-6 rounded-lg border border-white/5 bg-white/[0.03] p-4 text-xs text-slate-500">
              This verification page intentionally shows limited invoice proof only. It does not expose AWB lines, operational notes, addresses, or private portal records.
            </p>
          </>
        ) : (
          <>
            <div className="mb-6 flex items-center gap-3">
              <div className="rounded-full bg-red-500/10 p-3 text-red-300">
                <ShieldX className="h-7 w-7" />
              </div>
              <div>
                <h1 className="text-2xl font-bold">Invoice Not Found</h1>
                <p className="text-sm text-slate-500">This QR code could not be matched to a valid Ambara invoice record.</p>
              </div>
            </div>
          </>
        )}
      </Card>
    </main>
  );
}

function VerifyRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-4 border-b border-white/5 pb-3">
      <dt className="text-slate-500">{label}</dt>
      <dd className="text-right font-medium text-white">{value}</dd>
    </div>
  );
}
